### ISSUE TITLE
`FiftyOne` Import Failure

### ISSUE THREAD

**Issue by sjleo1** [boostcampaitech4lv23cv3/final-project-level3-cv-17#25]
### 내용
파이썬에서 fiftyone을 import하거나
```python
import fiftyone as fo
```
터미널에서 `fiftyone`을 입력하면 에러가 발생합니다.
```
(open-mmlab) root@d1f6f2a42208:~/final-project-level3-cv-17# fiftyone
```

### 에러 메시지
```
(open-mmlab) root@d1f6f2a42208:~/final-project-level3-cv-17# python utils/visualizer.py
Subprocess ['/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/opt/ml/.fiftyone/var/lib/mongo', '--logpath', '/opt/ml/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 127:
/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/fiftyone/db/bin/mongod: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "utils/visualizer.py", line 8, in <module>
    import fiftyone as fo
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/fiftyone/__public__.py", line 15, in <module>
    _foo.establish_db_conn(config)
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 156, in establish_db_conn
    port = _db_service.port
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/fiftyone/core/service.py", line 276, in port
    return self._wait_for_child_port()
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/fiftyone/core/service.py", line 170, in _wait_for_child_port
    return find_port()
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/fiftyone/core/service.py", line 168, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

### 시도해 본 방법
1. [`~/.fiftyone/config.json` 작성](https://docs.voxel51.com/user_guide/config.html#configuring-mongodb-connection)
    -> 또 다른 오류 발생
2. `apt-get install libcurl4-openssl-dev`
    -> 설치 실패
3. 등등등

**Comment by nanpuhaha** [comment]
이것도 한 번 해보시겠어요?
https://github.com/voxel51/fiftyone/issues/1988#issuecomment-1221583782

**Comment by sjleo1** [comment]
> 이것도 한 번 해보시겠어요? [voxel51/fiftyone#1988 (comment)](https://github.com/voxel51/fiftyone/issues/1988#issuecomment-1221583782)

```
(openmmlab) root@07f0fe312935:~/final-project-level3-cv-17/mmyolo# wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb -O libsll.deb && dpkg -i libsll.deb
--2023-01-25 07:16:59--  http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 185.125.190.36, 91.189.91.38, 91.189.91.39, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|185.125.190.36|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1301796 (1.2M) [application/x-debian-package]
Saving to: 'libsll.deb'

libsll.deb                   100%[==============================================>]   1.24M   754KB/s    in 1.7s

2023-01-25 07:17:02 (754 KB/s) - 'libsll.deb' saved [1301796/1301796]

(Reading database ... 17139 files and directories currently installed.)
Preparing to unpack libsll.deb ...
Unpacking libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.20) over (1.1.1-1ubuntu2.1~18.04.20) ...
Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.20) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
```

요렇게 설치 후에도 같은 에러가 발생했습니다 😢
