### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by nanpuhaha** [boostcampaitech4lv23cv3/final-project-level3-cv-17#27]
```python
uvicorn.run(
    app, host=config["server"]["host"], port=config["server"]["port"], reload=True
)

➜ python app/server.py
WARNING:  You must pass the application as an import string to enable 'reload' or 'workers'.
```

```python
uvicorn.run(
    "app.server:app", host=config["server"]["host"], port=config["server"]["port"], reload=True
)

➜ python app/server.py 
INFO:     Will watch for changes in these directories: ['/opt/ml/final-project-level3-cv-17']
INFO:     Uvicorn running on http://0.0.0.0:30001 (Press CTRL+C to quit)
INFO:     Started reloader process [4319] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/conda/envs/final2/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/final2/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/opt/conda/envs/final2/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/final2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/opt/conda/envs/final2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
```

**Comment by nanpuhaha** [comment]
`python app/server.py`로 실행하는 것이 아니라 `python -m app.server`로 실행해야 하는 하는 것으로 확인됨.

```diff
- python app/server.py
+ python -m app.server
```
