### ISSUE TITLE
연속해서 추론 시 발생 에러

### ISSUE THREAD

**Issue by Sungyu-Park** [boostcampaitech4lv23cv3/final-project-level3-cv-17#28]
```python
Traceback (most recent call last):
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/ml/final-project-level3-cv-17/app/server.py", line 170, in inference
    return _inference_image(model, body.media_filepath)
  File "/opt/ml/final-project-level3-cv-17/app/server.py", line 104, in _inference_image
    visualizer = VISUALIZERS.build(model.cfg.visualizer)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `DetLocalVisualizer` in mmdet/visualization/local_visualizer.py: <class 'mmdet.visualization.local_visualizer.DetLocalVisualizer'> instance named of visualizer has been created, the method `get_instance` should not access any other arguments
```

**Comment by Sungyu-Park** [comment]
MMYOLO의 `video_demo.py`를 활용하여 작성한 추론 코드에 아래와 같은 내용이 있습니다.
```python
visualizer = VISUALIZERS.build(model.cfg.visualizer)
```
[이 부분](https://github.com/boostcampaitech4lv23cv3/final-project-level3-cv-17/blob/mvp_backend/app/server.py#L111)에서 `DetLocalVisualizer` 클래스의 인스턴스가 생성되고 `Registry VISUALIZERS`에 등록 되는 것 같습니다.

```python
class DetLocalVisualizer(Visualizer):
    def __init__(self,
                 name: str = 'visualizer',
```
`local_visualizer.py`에 정의된 `DetLocalVisualizer`를 보면 이름의 기본값이 `visualizer`인 것을 알 수 있습니다. 제가 작성했던 코드에서는 객체의 이름을 별도로 지정해주지 않아서 처음 추론 시 `visualizer`라는 이름의 인스턴스가 생성되고, 이어서 추론을 했을 때는 이미 `Registry VISUALIZERS`에 있는 객체를 build_function으로 생성하려고 해서 발생했던 에러인 것 같습니다.
[visualizer 이름을 생성해주는 함수](https://github.com/boostcampaitech4lv23cv3/final-project-level3-cv-17/blob/mvp_backend/app/server.py#L101:L104)를 추가하니 해결되었습니다.
