### ISSUE TITLE
master branch에서 train 실행 시 에러

### ISSUE THREAD

**Issue by JKbin** [boostcampaitech4lv23cv3/final-project-level3-cv-17#33]
```python
Traceback (most recent call last):
  File "tools/train.py", line 116, in <module>
    main()
  File "tools/train.py", line 63, in main
    cfg = Config.fromfile(args.config)
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 172, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 404, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(base_cfg_path)
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 404, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(base_cfg_path)
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 404, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(base_cfg_path)
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 377, in _file2dict
    check_file_exist(filename)
  File "/opt/conda/envs/open-mmlab/lib/python3.8/site-packages/mmengine/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/opt/ml/final-project-level3-cv-17/mmyolo/configs/_emergency_/default_runtime.py" does not exist
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f1ef8893d30>
Traceback (most recent call last):
  File "/opt/conda/envs/open-mmlab/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/opt/conda/envs/open-mmlab/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp18qvivk4/tmp9s7j0b4n.py'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f1ef8893d30>
Traceback (most recent call last):
  File "/opt/conda/envs/open-mmlab/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/opt/conda/envs/open-mmlab/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpuhiueers/tmpluzumnvz.py'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f1ef8893d30>
Traceback (most recent call last):
  File "/opt/conda/envs/open-mmlab/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/opt/conda/envs/open-mmlab/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpps2rhot9/tmp6g165oze.py'
```

master 브랜치에서 훈련을 할려고 하니 이런 에러가 발생합니다.
```python
python tools/train.py configs/_emergency_/yolov8_ver4/yolov8_l_syncbn_fast_8xb16-500e_coco.py
```

구글링 해보니 [issue](https://github.com/open-mmlab/mmdetection/issues/2698)가 있어 확인해봤는데
라이브러리를 삭제하고 다시 다운로드 하라고 적혀있더라구요.
(아니면 config 문제라고 합니다..)

선규님은 master branch에서 훈련 해보셨나요??
아니면 이런 에러 보신 적 있으실까요?

**Comment by nanpuhaha** [comment]
저도 비슷한 에러가 나는데, 저는 중간에 `NameError: name 'pre_transform' is not defined`가 있다는 점이 다르네요.

```python
➜ python tools/train.py configs/_emergency_/yolov7_ver4/yolov7_d-p6_syncbn_fast_8x16b-300e_coco.py
Traceback (most recent call last):
  File "tools/train.py", line 116, in <module>
    main()
  File "tools/train.py", line 63, in main
    cfg = Config.fromfile(args.config)
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/mmengine/config/config.py", line 172, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/mmengine/config/config.py", line 404, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(base_cfg_path)
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/mmengine/config/config.py", line 404, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(base_cfg_path)
  File "/opt/conda/envs/final2/lib/python3.8/site-packages/mmengine/config/config.py", line 432, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "", line 132, in <module>
NameError: name 'pre_transform' is not defined
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f9822da8820>
Traceback (most recent call last):
  File "/opt/conda/envs/final2/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/opt/conda/envs/final2/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgmsgs0ng/tmp4kejzi6u.py'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f9822da8820>
Traceback (most recent call last):
  File "/opt/conda/envs/final2/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/opt/conda/envs/final2/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp1hjz1thw/tmpo28n_sb7.py'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f9822da8820>
Traceback (most recent call last):
  File "/opt/conda/envs/final2/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/opt/conda/envs/final2/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp0rpe9ros/tmpvhkftv3w.py'
```

**Comment by JKbin** [comment]
```python
FileNotFoundError: file "/opt/ml/final-project-level3-cv-17/mmyolo/configs/_emergency_/default_runtime.py" does not exist
```
default_runtime.py 경로 변경으로 해결
